@ExRateApiXml_HostAddress = http://localhost:28539

POST {{ExRateApiXml_HostAddress}}/api/exchange/
Content-Type: application/xml
Accept: application/xml

<ExchangeRateRequest>
  <FromCurrency>USD</FromCurrency>
  <ToCurrency>EUR</ToCurrency>
  <Amount>100</Amount>
</ExchangeRateRequest>

###
